### ISSUE TITLE
Requires plugins, consumers, credentials

### ISSUE THREAD

**Issue by SamKirsch10** [liyuntao/kong-init#17]
Hi,
First, thanks so much for this amazing tool! It makes our lives much, MUCH easier.

It looks like the latest version is requiring a plugins, consumers, and credentials section. These should be optional, right? If I have a file like below, it will error about a plugins section, then a consumers section, then a credentials section.

```
--- 
services:
  - name: test.local
    url: test.local
routes:
  - name: test.local
    apply_to: test.local
    config:
      hosts:
         - test.local
       methods: 
         - GET
```
