### ISSUE TITLE
basic-auth example

### ISSUE THREAD

**Issue by mwesox** [liyuntao/kong-init#9]
Hi , 

do you support also basic-auth ? If so, do you have an example? Are we able to provide credentials on consumer level? 

thx

**Comment by liyuntao** [comment]
Yeah, kong-init do support [basic-auth](https://docs.konghq.com/plugins/basic-authentication) plugin, but not on consumer level yet.

e.g. in version 1 (under api definition):
```yaml
plugins:
- name: whatever-just-a-description
  plugin_type: basic-auth
  target_api: cookie-api # can be applied to global/apis
  config:
    hide_credentials: false
```

or in version 2(under service/route definition):

```yaml
plugins:
- name: basic-auth # type of plugin here
  enabled: true
  target: s[netdisk,dummy] # can be applied to services/routes/global
  config:
    hide_credentials: false
```

In fact, kong-init will just passing the `plugins.config` struct to kong-admin-api, thus support any independent plugin out of the box. 

However plugins/credentials on consumer level is currently not supported yet. Do you have anything to share on the specific scene about consumer level credentials? (currently we are using a simple micro-service for creating credentials and sign JWT-token when user doing login action)
